### ISSUE TITLE
Need a Filter

### ISSUE THREAD

**Issue by alefort** [alefort/getcrafty#3]
Since we have a slew of data for each product at a store, I'd like a simple filtering/sorting feature on the product list at a store.

At the very list, I'd like to filter by Country of origin and by tertiary/secondary type.

Any idea what the UI for the filter could be?

**Comment by scottblinch** [comment]
How about this?: https://moqups.com/scott@tbkcreative.com/ia7PUkfP/p:aa27bb85c

**Comment by alefort** [comment]
Me like. Make it so.

**Comment by scottblinch** [comment]
I'm going to build the filter list in a similar fashion that I did the dHub one, which was to loop through all the products and grab all existing relevant properties for a certain filter. This is only because I can't think of a better way to do it. I feel like there is a more efficient way of building the filter list, but I can't seem to find any solutions.

Any thoughts?

**Comment by alefort** [comment]
How about, just a search box, like on dhub? Typing into it filters the results, no need to select filter options?

**Comment by scottblinch** [comment]
Woof! Just saw this now. Yep, we can do that. Would certainly make things simpler.

**Comment by scottblinch** [comment]
Stuck my filter stuff in a different branch in case we ever decide to return to it in the future and added the text search filter that filters on everything.

**Comment by alefort** [comment]
I see the text search filter now, lovely and works as expected. I'll close this and open a new issue for the styling
